# dbt_project.yml

name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    prestage_1:
      +schema: raw
    stage:
      +schema: stage
    example:
      +materialized: table

on-run-end:
   "{{log_dbt_results(results)}}"
