WITH FSCMTOPMODELAM_FINEXTRACTAM_GL as (select * from raw.fscmtopmodelam_finextractam_glbiccextractam_ledgerextractpvo),
CT_GL_LEDGERS_D_STG as (
select
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERLEDGERID AS LEDGER_ID,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERCHARTOFACCOUNTSID AS COA_ID,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERNAME AS LEDGER_NAME,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERSHORTNAME AS LEDGER_SHORT_NAME,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERDESCRIPTION AS DESCRIPTION,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERLEDGERCATEGORYCODE AS LEDGER_CATEGORY_CODE,
  (
    CASE WHEN FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGEROBJECTTYPECODE = 'L' then 'Ledger' when FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGEROBJECTTYPECODE = 'S' then 'Ledger Set' Else FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGEROBJECTTYPECODE END
  ) AS LEDGER_TYPE,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERCURRENCYCODE AS LEDGER_CURR_CODE,
  CAST(
    FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERCREATIONDATE AS STRING
  ) AS CREATION_DT, --In the Data we have only 'N' value
  CAST(
    FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERLASTUPDATEDATE AS DATE
  ) AS LAST_UPDATE_DT,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERCREATEDBY AS CREATED_BY,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERLASTUPDATEDBY AS LAST_UPDATED_BY,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERLEDGERID AS INTEGRATION_ID,
  1000 AS DATASOURCE_NUM_ID,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERLEDGERCATEGORYCODE AS LEDGER_CAT_CODE,
  FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERSLABALBYLEDGERCURRFLAG AS CURRENT_FLAG,
  NULL AS ATTRIBUTE1,
  NULL AS ATTRIBUTE2,
  NULL AS ATTRIBUTE3,
  NULL AS ATTRIBUTE4,
  NULL AS ATTRIBUTE5
from
   FSCMTOPMODELAM_FINEXTRACTAM_GL
)
SELECT * FROM CT_GL_LEDGERS_D_STG