WITH FSCMTOPMODELAM_FINEXTRACTAM_GL AS (SELECT * FROM raw.fscmtopmodelam_finextractam_glbiccextractam_ledgerextractpvo),
FSCMTOPMODELAM_FINEXTRACTAM__1 AS (SELECT * FROM raw.fscmtopmodelam_finextractam_glbiccextractam_fiscalperiodextractpvo),
FSCMTOPMODELAM_FINEXTRACTAM__2 AS (SELECT * FROM raw.fscmtopmodelam_finextractam_glbiccextractam_balanceextractpvo),
R AS (SELECT * FROM raw.fscmtopmodelam_finextractam_glbiccextractam_dailyrateextractpvo),
CT_GL_BALANCES_F_STG AS (
  SELECT
    CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCELEDGERID AS STRING) AS LEDGER_ID,
    CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCECODECOMBINATIONID AS STRING) AS GLCC_ID,
    CONCAT(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNAME, '~', FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERPERIODSETNAME) AS PERIOD_ID,
    CAST(FORMAT_TIMESTAMP('%Y%m%d', TIMESTAMP(FSCMTOPMODELAM_FINEXTRACTAM__1.PERIODENDDATE)) AS INT64) AS PERIOD_DT_ID,
    FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNAME AS PERIOD_NAME,
    CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODYEAR AS STRING) AS PERIOD_YEAR,
    CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNUM AS STRING) AS PERIOD_NUM,
    FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERNAME AS LEDGER_NAME,
    FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCECURRENCYCODE AS CURRENCY_CODE,
    FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEACTUALFLAG AS ACTUAL_FLAG,
   CASE
      WHEN FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETDR > FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETCR
      THEN 'DB'
      ELSE 'CR'
    END AS DB_CR_IND,
    FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCETRANSLATEDFLAG AS TRANSLATED_FLAG,
    CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEOBJECTVERSIONNUMBER AS INT64) AS BUDGET_VERSION_ID,
    CAST(NULLIF(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEENCUMBRANCETYPEID, '') AS INT64) AS ENCUMBRANCE_TYPE_ID,
    CASE
      WHEN FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEACTUALFLAG = 'E' THEN 'Y'
      ELSE 'N'
    END AS ENCUMBRANCE_TYPE_NAME,
    CASE
      WHEN FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCETRANSLATEDFLAG IS NULL THEN 'Y'
      ELSE 'N'
    END AS SUMMARY_ACCOUNT_FLAG,
    NULLIF(NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETDR AS INT64), 0), 0) AS PERIOD_NET_DR,
    NULLIF(NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETCR AS INT64), 0), 0) AS PERIOD_NET_CR,
    NULLIF(NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEBEGINBALANCEDR AS INT64), 0), 0) AS BEGIN_BALANCE_DR,
    NULLIF(NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEBEGINBALANCECR AS INT64), 0), 0) AS BEGIN_BALANCE_CR,
    NULLIF(NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEBEGINBALANCECR AS INT64), 0) - NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEBEGINBALANCEDR AS INT64), 0), 0) AS BEGIN_BALANCE,
    NULLIF((NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEBEGINBALANCECR AS INT64), 0) - NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEBEGINBALANCEDR AS INT64), 0)) - (NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETCR AS INT64), 0) - NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETDR AS INT64), 0)), 0) AS END_BALANCE,
    NULLIF(NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETCR AS INT64), 0) - NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETDR AS INT64), 0), 0) AS PERIOD_ACTIVITY,
    NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEQUARTERTODATEDR AS INT64), 0) AS QTR_TO_DATE_DR,
    NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEQUARTERTODATECR AS INT64), 0) AS QTR_TO_DATE_CR,
    NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETDR AS INT64), 0) * NULLIF(CAST(R.DAILYRATECONVERSIONRATE AS INT64), 1) AS PERIOD_NET_DR_USD,
    NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETCR AS INT64), 0) * NULLIF(CAST(R.DAILYRATECONVERSIONRATE AS INT64), 1) AS PERIOD_NET_CR_USD,
    NULLIF((NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEBEGINBALANCECR AS INT64), 0) - NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEBEGINBALANCEDR AS INT64), 0)) * NULLIF(CAST(R.DAILYRATECONVERSIONRATE AS INT64), 1), 0) AS BEGIN_BALANCE_USD,
    NULLIF((NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEBEGINBALANCECR AS INT64), 0) - NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEBEGINBALANCEDR AS INT64), 0)) - (NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETCR AS INT64), 0) - NULLIF(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETDR AS INT64), 0)) * NULLIF(CAST(R.DAILYRATECONVERSIONRATE AS INT64), 1), 0) AS END_BALANCE_USD,
    NULLIF(CAST(R.DAILYRATECONVERSIONRATE AS INT64), 1) AS CONV_RATE_TO_USD,
    NULLIF(R.DAILYRATECONVERSIONTYPE, 'Corporate') AS CONV_RATE_TYPE,
    CAST(FSCMTOPMODELAM_FINEXTRACTAM__1.PERIODCREATIONDATE AS DATE) AS CREATION_DT,
    CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCELASTUPDATEDATE AS DATE) AS LAST_UPDATE_DT,
    FSCMTOPMODELAM_FINEXTRACTAM__1.PERIODCREATEDBY AS CREATED_BY,
    FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCELASTUPDATEDBY AS LAST_UPDATED_BY,
    NULLIF(
    CONCAT(
    COALESCE(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCELEDGERID AS STRING), ''), '~',
    COALESCE(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCECODECOMBINATIONID AS STRING), ''), '~',
    COALESCE(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNAME AS STRING), ''), '~',
    CASE
      WHEN COALESCE(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETDR AS INT64), 0) > COALESCE(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNETCR AS INT64), 0)
      THEN 'DB'
      ELSE 'CR'
    END, '~',
    COALESCE(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEACTUALFLAG AS STRING), ''), '~',
    COALESCE(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCETRANSLATEDFLAG AS STRING), 'X'), '~',
    COALESCE(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCECURRENCYCODE AS STRING), ''), '~',
    COALESCE(CAST(FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEOBJECTVERSIONNUMBER AS STRING), '0')
    ),
    '0'
    ) AS INTEGRATION_ID,
    1000 AS DATASOURCE_NUM_ID,
    'Y' AS ACTIVE_FLAG,
    'N' AS DELETE_FLAG,
    '-' AS SEGMENT1,
    '-' AS SEGMENT2,
    '-' AS SEGMENT3,
    '-' AS SEGMENT4,
    '-' AS SEGMENT5,
    '-' AS SEGMENT6,
    '-' AS SEGMENT7,
    '-' AS SEGMENT8,
    '-' AS SEGMENT9,
    '-' AS ATTRIBUTE1,
    '-' AS ATTRIBUTE2,
    '-' AS ATTRIBUTE3,
    '-' AS ATTRIBUTE4,
    '-' AS ATTRIBUTE5,
    '-' AS ATTRIBUTE6,
    '-' AS ATTRIBUTE7,
    '-' AS ATTRIBUTE8,
    '-' AS ATTRIBUTE9,
    '-' AS ATTRIBUTE10
  FROM
    FSCMTOPMODELAM_FINEXTRACTAM_GL
  INNER JOIN
    FSCMTOPMODELAM_FINEXTRACTAM__1
  ON
    FSCMTOPMODELAM_FINEXTRACTAM__1.PERIODPERIODSETNAME = FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERPERIODSETNAME
  INNER JOIN
    FSCMTOPMODELAM_FINEXTRACTAM__2
  ON
    FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCELEDGERID = CAST(FSCMTOPMODELAM_FINEXTRACTAM_GL.LEDGERLEDGERID AS STRING)
    AND FSCMTOPMODELAM_FINEXTRACTAM__1.PERIODPERIODNAME = FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCEPERIODNAME
  LEFT JOIN
    R
  ON
    R.DAILYRATEFROMCURRENCY = FSCMTOPMODELAM_FINEXTRACTAM__2.BALANCECURRENCYCODE
    AND R.DAILYRATETOCURRENCY = 'USD'
    AND R.DAILYRATECONVERSIONTYPE = 'Corporate'
    AND CAST(R.DAILYRATECONVERSIONDATE AS DATE) = CAST(FSCMTOPMODELAM_FINEXTRACTAM__1.PERIODENDDATE AS DATE)
)
SELECT * FROM CT_GL_BALANCES_F_STG